Repository nextcloud-libraries/nextcloud-axios, pull requests merged in 2022-01, with the labels that each got.

#380 Update npm and node engines versions
  package.json
Labels: dependencies

#403 Bump axios from 0.24.0 to 0.25.0
  package-lock.json
  package.json
Labels: dependencies, 3. to review, priority

#404 1.9.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review
