Repository nextcloud-libraries/nextcloud-axios, pull requests merged in 2022-08, with the labels that each got.

#492 Update npm and node engines versions
  package.json
Labels: dependencies

#494 v1.11.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#438 Bundle improvements
  .github/dependabot.yml
  .github/workflows/doc-publish.yml
  .github/workflows/publish.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  README.md
  babel.config.js
  package-lock.json
  package.json
  rollup.config.js
  test/index.test.js
  tsconfig.json
Labels: enhancement, 3. to review
