Repository nextcloud-libraries/nextcloud-axios, pull requests merged in 2024-04, with the labels that each got.

#640 chore: update workflows from templates
  .github/workflows/documentation.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/node-test.yml
  .github/workflows/npm-publish.yml
Labels: dependencies, 3. to review, automated

#655 feat: Export `isAxiosError` and axios types
  lib/index.ts
Labels: enhancement, 3. to review

#654 fix: Adjust badges and links in README
  README.md
Labels: 3. to review

#653 fix(ci): Update workflows from organization
  .github/workflows/documentation.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/node-test.yml
  .github/workflows/npm-publish.yml
Labels: 3. to review

#652 fix: Update NPM to v10 for LTS Node version 20
  package-lock.json
  package.json
Labels: 3. to review

#656 chore: Prepare 2.5.0 release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review
